name: Up To Date for minute

on:
  push:
  workflow_dispatch:

jobs:
  upstream:
    name: Update Upstream
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          
      - name: Configure Git
        if: steps.check.outputs.needs == 'true'
        run: git config --global user.email "action@github.com" && git config --global user.name "Github Action"

      - name: Update upstream
        run: ./scripts/Upstream.sh
      
      - name: Apply patches(1차 패치 적용)
        run: ./gradlew applyPatches
        
      - name: Check build
        run: ./gradlew build

      - name: Commit changes
        if: steps.check.outputs.needs == 'true'
        run: git add . && printf "Updated Upstream (Paper)\n\nUpstream has released updates that appear to apply and compile correctly\n\n$(cat compare.txt)" | git commit -F -

      - name: Push changes
        if: steps.check.outputs.needs == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
